;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sat Nov 12 2022
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
.MODEL SMALL
.STACK 100
.DATA
CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE
CPY PROC FAR
   
LOP:
   MOV DI,0H
   MOV AX,4000H
   MOV DS,AX
   MOV AL,[DI]
   MOV DX,2000H
   MOV DS,DX
   MOV [DI],AL
   ADD DI,1
   SUB CX,1
   CMP CX,0
   JNZ LOP
   RET
CPY ENDP
START:
	MOV AX,4000H
	MOV DS,AX
	MOV DI,4H
	MOV AX,5H
;	MOV CX,9FFFH
	MOV AX,[DI]
	MOV CX,5H
;	AGAIN: LOOP AGAIN
	CALL CPY
	JMP START
	 ; end delay

ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START